export const GET_ALBUMS_START = 'GET_ALBUMS_START';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_FAIL = 'GET_ALBUMS_FAIL';
export const GET_ALBUMS = 'GET_ALBUMS';

export const GOT_TO_NAV = 'GO_TO_NAV';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';
